### ISSUE TITLE
Using the generated java code

### ISSUE THREAD

**Issue by josecm** [protegeproject/code-generation#10]
I'm trying to use the generated java code by this plugin in protége. However, compilation fails with the following error in various functions of the created Factory. For a protege class called Binding:

![screenshot_1](https://user-images.githubusercontent.com/5178376/32060240-1ae61ca6-ba66-11e7-9664-5c0cbddd59c4.png)

The same happens for all getWrappedIndividual calls.

**Comment by csnyulas** [comment]
Have you tried the quick fix?
Unfortunately, it is really hard to tell what the problem is,without seeing the generated code and knowing what setup you are using. My best guess is that this is due to some version incompatibility between the libraries that you are using to compile the code, and the version of Protege that this code was create with.

**Comment by josecm** [comment]
Sorry for the trouble. Already detected the problem. The ontology had a class named String which overshadowed the Java class. Really sorry, the ontology was not devised by me, so I had no idea :(

**Comment by csnyulas** [comment]
Yes, that is a known issue with the code generator (i.e. class names that conflict with "reserved" Java class names). Thanks for the clarification!
