### ISSUE TITLE
code generation is not generating data and object properties whose domain is a composition of multiple classes

### ISSUE THREAD

**Issue by sagilar** [protegeproject/code-generation#12]
Hi,

I am using the code generation feature to deploy my ontology in the java runtime.
I realized that the properties which have a domain composed by multiple classes with the `OR` statement are not being generated in the java interfaces as properties. It applies for both data and object properties.
Please see the picture below:
![image](https://user-images.githubusercontent.com/36315612/52031105-e38a1200-24e8-11e9-9508-dbc6fe7d2f14.png)
![image](https://user-images.githubusercontent.com/36315612/52031200-5dba9680-24e9-11e9-93a8-aec83af170f2.png)
![image](https://user-images.githubusercontent.com/36315612/52031212-6ca14900-24e9-11e9-9b5e-bee3f73e524f.png)

When the range is composed with several classes it works fine. The problem only occurs when the domain is composed by several classes, as showed in the pics.

What can I do instead of modifying the code manually to add the properties?

P.S: I am using Protégé version 5.2, but I've used 5.5 as well and the problem occurs too.

Many thanks in advance.

**Comment by csnyulas** [comment]
I remember this being reported on the mailing list a long time ago, and at that time I looked at possible solutions. Unfortunately, if I remember correctly, there was no straightforward solution to this. I think the problem was that while in Java functions can be overwritten by reusing the same function name but making them take different arguments (e.g. the different classes that appear in the range), their return value always needs to be the exact same class. Which means that in case of disjunctions in the domain, an artificial class has to be created by the code generator, and that can be an difficult and potentially intractable problem.

If the code generation is something important for you to use with your ontology, I would recommend that you try one of these two workarounds in the model, in order to avoid the bug:
- instead of the explicit disjunction of classes in the domain, use the their most specific common ancestor, or if there is no such class you can use `owl:Thing` or nothing at all.
- you could replace the disjunctions in domains with an artificial class that you would create that represents the disjunctions of those classes (e.g. you could create a class called `StateOrSubsequenceOrTransition`, and declare it equivalent with `State or Subsequence or Transition`)

**Comment by sagilar** [comment]
Thanks for the quick response.

Yes, I need the generated code.
I will try to fix the problem with your suggestions by keeping a different version (file) for the ontology generation and the original one to keep the ontology as it must be.
I think the parent class could be a good solution (I did it for a property that fitted a parent class).
